name: sharding-repl-cache

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  configSrv-1:
    image: mongo:6
    command: mongod --configsvr --replSet configRS --port 27019 --bind_ip_all
    ports:
      - "27019:27019"

  configSrv-2:
    image: mongo:6
    command: mongod --configsvr --replSet configRS --port 27019 --bind_ip_all

  configSrv-3:
    image: mongo:6
    command: mongod --configsvr --replSet configRS --port 27019 --bind_ip_all

  shard1-1:
    image: mongo:6
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all

  shard1-2:
    image: mongo:6
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all

  shard1-3:
    image: mongo:6
    command: mongod --shardsvr --replSet shard1RS --port 27018 --bind_ip_all

  shard2-1:
    image: mongo:6
    command: mongod --shardsvr --replSet shard2RS --port 27018 --bind_ip_all

  shard2-2:
    image: mongo:6
    command: mongod --shardsvr --replSet shard2RS --port 27018 --bind_ip_all

  shard2-3:
    image: mongo:6
    command: mongod --shardsvr --replSet shard2RS --port 27018 --bind_ip_all

  mongos:
    image: mongo:6
    depends_on:
      - configSrv-1
      - configSrv-2
      - configSrv-3
    command: mongos --configdb configRS/configSrv-1:27019,configSrv-2:27019,configSrv-3:27019 --bind_ip_all
    ports:
      - "27017:27017"

  api:
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
      - redis
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "8080:8000"